### ISSUE TITLE
views: handle elasticsearch errors

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-records-rest#84]
If you use `invenio_records_rest.query.es_search_factory` and the search phrase is invalid `elasticsearch_py` will raise an error which will result in a HTTP 500 error. Instead we should handle the error and reply with HTTP 400, and a proper error message explaining that the query was invalid.

Below is a stack trace of the error:

``` trackback
Stacktrace (most recent call last):

  File "flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "invenio_rest/views.py", line 206, in dispatch_request
    .dispatch_request(*args, **kwargs)
  File "flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "invenio_records_rest/views.py", line 424, in get
    search_result = search.execute()
  File "elasticsearch_dsl/search.py", line 579, in execute
    **self._params
  File "elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "elasticsearch/client/__init__.py", line 548, in search
    doc_type, '_search'), params=params, body=body)
  File "elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "elasticsearch/connection/http_requests.py", line 84, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
```

**Comment by lnielsen** [comment]
``/?q=filetype:``

**Comment by JavierDelgadoFernandez** [comment]
@lnielsen In the case of Zenodo, the problem comes from OAuth:
```
Traceback (most recent call last):
  File "/home/javier/Documents/zenodo_sprint/env24/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/javier/Documents/zenodo_sprint/env24/lib/python3.5/site-packages/werkzeug/wsgi.py", line 659, in __call__
    return app(environ, start_response)
  File "/home/javier/Documents/zenodo_sprint/env24/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/javier/Documents/zenodo_sprint/env24/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/javier/Documents/zenodo_sprint/env24/lib/python3.5/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/javier/Documents/zenodo_sprint/env24/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/javier/Documents/zenodo_sprint/env24/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/javier/Documents/zenodo_sprint/env24/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/javier/Documents/zenodo_sprint/env24/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/javier/Documents/zenodo_sprint/env24/lib/python3.5/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/javier/Documents/zenodo_sprint/env24/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/javier/Documents/zenodo_sprint/env24/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/javier/Documents/zenodo_sprint/env24/lib/python3.5/site-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/javier/Documents/zenodo_sprint/env24/lib/python3.5/site-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/home/javier/Documents/zenodo_sprint/env24/src/invenio-oauth2server/invenio_oauth2server/ext.py", line 148, in verify_oauth_token_and_set_current_user
    uri, http_method, body, headers, scopes
  File "/home/javier/Documents/zenodo_sprint/env24/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "/home/javier/Documents/zenodo_sprint/env24/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/endpoints/resource.py", line 68, in verify_request
    request = Request(uri, http_method, body, headers)
  File "/home/javier/Documents/zenodo_sprint/env24/lib/python3.5/site-packages/oauthlib/common.py", line 395, in __init__
    self._params.update(dict(urldecode(self.uri_query)))
  File "/home/javier/Documents/zenodo_sprint/env24/lib/python3.5/site-packages/oauthlib/common.py", line 129, in urldecode
    raise ValueError(error % (set(query) - urlencoded, query))
ValueError: Error trying to decode a non urlencoded string. Found invalid characters: {':'} in the string: 'page=1&q=type:&size=20'. Please ensure the request/response body is x-www-form-urlencoded.
```

I can try to catch the exception in ``invenio-oauth2server`` to send one more descriptive. ``InvalidURL``?

**Comment by lnielsen** [comment]
This problem still exists on Python 2.7

**Comment by kaplun** [comment]
In INSPIRE we have seen something similar. If a record is not yet in ES (because the index need still to be refreshed) there is an unhandled exception:
```
../../local/lib/python2.7/site-packages/invenio_rest/views.py:207: in dispatch_request
    *args, **kwargs
../../local/lib/python2.7/site-packages/flask/views.py:149: in dispatch_request
    return meth(*args, **kwargs)
../../local/lib/python2.7/site-packages/invenio_records_rest/views.py:282: in inner
    return f(self, pid=pid, record=record, *args, **kwargs)
../../local/lib/python2.7/site-packages/invenio_records_rest/views.py:322: in need_record_permission_decorator
    return f(self, record=record, *args, **kwargs)
../../local/lib/python2.7/site-packages/invenio_records_rest/views.py:553: in get
    self.check_if_modified_since(record.updated, etag=etag)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = {}

    @property
    def updated(self):
        """Get last updated timestamp."""
>       return arrow.get(self['_updated']).naive
E       KeyError: '_updated'
```

because `self` is `{}`.

Is this connected with this bug? Or shall we open a new issue?

**Comment by lnielsen** [comment]
@kaplun I think this is an new issue. But isn't it related to that you serve the GET /records/:id from your own record class and that this is a bug in that class?

**Comment by lnielsen** [comment]
https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/records/es_record.py#L62

**Comment by kaplun** [comment]
:flushed:
